dist: trusty
language: go
go:
  - 1.11.x
  - master
matrix:
  allow_failures:
    - go: master
script:
  - make test-cover
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_script:
  - make clean
