apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDBBackup
metadata:
  finalizers:
  - delete-backup
  name: backup1
spec:
  clusterName: cluster1
  storageName: minio
  type: physical
#  compressionType: gzip
#  compressionLevel: 6
