apiVersion: "cache.example.com/v1alpha1"
kind: "PerconaServerMongoDB"
metadata:
  name: "percona-server-mongodb"
spec:
  size: 1 
  mongodb:
    port: 27017
    storageEngine: wiredTiger
    replicaSetName: rs0
