apiVersion: "psmdb.percona.com/v1alpha1"
kind: "PerconaServerMongoDB"
metadata:
  name: "percona-server-mongodb"
spec:
  size: 1 
  image: percona/percona-server-mongodb:3.6
  mongodb:
    port: 27017
    storageEngine: wiredTiger
    replicaSetName: rs0
