apiVersion: psmdb.percona.com/v1alpha1
kind: PerconaServerMongoDB
metadata:
  name: my-cluster-name
spec:
  version: "3.6"
  secrets:
    key: my-cluster-name-mongodb-key
    users: my-cluster-name-mongodb-users
  replsets:
  - name: rs0
    size: 3
  mongod:
    port: 27017
    hostPort: 0
    resources:
      limits:
        cpu: "300m"
        memory: "0.5G"
        storage: "1Gi"
      requests:
        cpu: "300m"
        memory: "0.5G"
    storageEngine: wiredTiger
    operationProfiling:
      mode: slowOp
      slowOpThresholdMs: 100
