apiVersion: psmdb.percona.com/v1alpha1
kind: PerconaServerMongoDB
metadata:
  name: my-cluster-name
spec:
  version: "3.6"
  secrets:
    key: my-cluster-name-mongodb-key
    users: my-cluster-name-mongodb-users
  mongod:
<<<<<<< Updated upstream
    size: 3
    replsetName: rs0
    port: 27017
    hostPort: 0
=======
    net:
      port: 27017
      hostPort: 0
>>>>>>> Stashed changes
    resources:
      limits:
        cpu: "300m"
        memory: "0.5G"
        storage: "1Gi"
      requests:
        cpu: "300m"
        memory: "0.5G"
    storage:
      engine: wiredTiger
      wiredTiger:
        cacheSizeRatio: 0.5
    operationProfiling:
      mode: slowOp
<<<<<<< Updated upstream
      slowMs: 100
=======
      slowOpThresholdMs: 100
    #auditLog:
    #  destination: file
    #  format: BSON
    #  filter: '{}'
    #  resources:
    #    limits:
    #      storage: "1Gi"
>>>>>>> Stashed changes
