apiVersion: psmdb.percona.com/v1alpha1
kind: PerconaServerMongoDB
metadata:
  name: my-cluster-name
spec:
  version: "3.6"
  secrets:
    key: my-cluster-name-mongodb-key
    users: my-cluster-name-mongodb-users
  replsets:
  - name: rs0
    size: 3
  mongod:
    net:
      port: 27017
      hostPort: 0
    resources:
      limits:
        cpu: "300m"
        memory: "0.5G"
        storage: "1Gi"
      requests:
        cpu: "300m"
        memory: "0.5G"
    security:
      redactClientLogData: false
    setParameter:
      wiredTigerConcurrentReadTransactions: 128
      wiredTigerConcurrentWriteTransactions: 128
    storage:
      engine: wiredTiger
      wiredTiger:
        cacheSizeRatio: 0.5
    operationProfiling:
      mode: slowOp
      slowOpThresholdMs: 100
      rateLimit: 1
    #auditLog:
    #  destination: file
    #  format: BSON
    #  filter: '{}'
    #  resources:
    #    limits:
    #      storage: "1Gi"
