apiVersion: psmdb.percona.com/v1alpha1
kind: PerconaServerMongoDB
metadata:
  name: my-cluster-name
spec:
  #platform: openshift
  version: "3.6.8"
  imagePullPolicy: Always
  secrets:
    key: my-cluster-name-mongodb-key
    users: my-cluster-name-mongodb-users
  replsets:
    - name: rs0
      size: 3
      arbiter:
        enabled: false
        size: 1
      expose:
        enabled: false
        exposeType: ClusterIP
      resources:
        limits:
          cpu: "300m"
          memory: "0.5G"
          storage: "3Gi"
        requests:
          cpu: "300m"
          memory: "0.5G"
        #storageClass: aws-gp2
  mongod:
    net:
      port: 27017
      hostPort: 0
    security:
      redactClientLogData: false
    setParameter:
      ttlMonitorSleepSecs: 60
      wiredTigerConcurrentReadTransactions: 128
      wiredTigerConcurrentWriteTransactions: 128
    storage:
      engine: wiredTiger
      inMemory:
        engineConfig:
          inMemorySizeRatio: 0.9
      mmapv1:
        nsSize: 16
        smallfiles: false
      wiredTiger:
        engineConfig:
          cacheSizeRatio: 0.5
          directoryForIndexes: false
          journalCompressor: snappy
        collectionConfig:
          blockCompressor: snappy
        indexConfig:
          prefixCompression: true
    operationProfiling:
      mode: slowOp
      slowOpThresholdMs: 100
      rateLimit: 1
    #auditLog:
    #  destination: file
    #  format: BSON
    #  filter: '{}'
  backup:
    enabled: false
    version: 0.3.0
    restartOnFailure: true
    coordinator:
      resources:
        limits:
          cpu: "100m"
          memory: "0.2G"
          storage: "1Gi"
        requests:
          cpu: "100m"
          memory: "0.1G"
        #storageClass: aws-gp2
      debug: false
    storages:
      s3-us-west:
        type: s3
        s3:
          bucket: S3-BACKUP-BUCKET-NAME-HERE
          credentialsSecret: my-cluster-name-backup-s3
          region: us-west-2
      #minio:
      #  type: s3
      #  s3:
      #    bucket: MINIO-BACKUP-BUCKET-NAME-HERE
      #    credentialsSecret: my-cluster-name-backup-minio
      #    endpointUrl: http://minio.example.local:9000/minio/
    tasks:
    - name: daily
      enabled: true
      schedule: "0 0 * * *"
      storageName: s3-us-west
      compressionType: gzip
    - name: weekly
      enabled: false
      schedule: "0 0 * * 0"
      storageName: s3-us-west
      compressionType: gzip
