apiVersion: "psmdb.percona.com/v1alpha1"
kind: "PerconaServerMongoDB"
metadata:
  name: "percona-server-mongodb"
  namespace: "psmdb"
spec:
  size: 3 
  image: percona/percona-server-mongodb:3.6
  mongod:
    replsetName: rs0
    port: 27017
    hostPort: 0
    resources:
      limits:
        cpu: 1
        memory: 0.5Gi
        storage: 3Gi
      requests:
        cpu: 0.5
        memory: 0.5Gi
        storage: 1Gi
    storageEngine: wiredTiger
    operationProfiling:
      slowMs: 100
