apiVersion: psmdb.percona.com/v1alpha1
kind: PerconaServerMongoDB
metadata:
  name: my-cluster-name
spec:
  image: percona/percona-server-mongodb:3.6
  secrets:
    key: percona-server-mongodb-key
    users: percona-server-mongodb-users
  mongod:
    size: 3
    replsetName: rs0
    port: 27017
    hostPort: 0
    resources:
      limits:
        cpu: "300m"
        memory: "0.5G"
        storage: "1Gi"
      requests:
        cpu: "300m"
        memory: "0.5G"
    storageEngine: wiredTiger
    operationProfiling:
      mode: slowOp
      slowMs: 100
    volumeClassName: standard
