apiVersion: psmdb.percona.com/v1alpha1
kind: PerconaServerMongoDB
metadata:
  name: local-balancer
spec:
  #platform: openshift
  image:
  secrets:
    users: some-users
  replsets:
  - name: rs0
    size: 3
    resources:
      storage: "1Gi"
    expose:
      enabled: true
      exposeType: LoadBalancer
